// Code generated by ogen, DO NOT EDIT.
package api

type RacePostRes interface {
	racePostRes()
}

type RaceRaceIDGetRes interface {
	raceRaceIDGetRes()
}

type RaceRaceIDResultsGetRes interface {
	raceRaceIDResultsGetRes()
}

type ResultsPostRes interface {
	resultsPostRes()
}
